apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-wasm-module
  namespace: wasm-system
binaryData:
  module.wasm: ''  # Will be populated by deploy script
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-wasm
  namespace: wasm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-wasm
  template:
    metadata:
      labels:
        app: hello-wasm
    spec:
      containers:
      - name: hello-wasm
        image: wasmedge/slim:latest
        imagePullPolicy: Always
        command: ["wasmedge"]
        args: ["/wasm/module.wasm"]
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: wasm-module
          mountPath: /wasm
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: wasm-module
        configMap:
          name: hello-wasm-module
          items:
          - key: module.wasm
            path: module.wasm
---
apiVersion: v1
kind: Service
metadata:
  name: hello-wasm
  namespace: wasm-system
spec:
  selector:
    app: hello-wasm
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort 