apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wasmfunctions.wasm.bits-dissertation.io
spec:
  group: wasm.bits-dissertation.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                runtime:
                  type: string
                source:
                  type: string
                function:
                  type: string
  scope: Namespaced
  names:
    plural: wasmfunctions
    singular: wasmfunction
    kind: WasmFunction
    shortNames:
    - wf
